/* Generated by AN DISI Unibo */ 
package it.unibo.ctxwaiterwalker
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "tearoom_covid19_sprint1.pl", "sysRules.pl"
	)
}

